Added MongoDB support
andrewda/CSGOItemDB.com pull request #14
Opened 2017-02-27 15:41 UTC by MartijnVegter

This should fix #8

2017-02-27 17:58 UTC, andrewda requested changes
Thanks for this, looks good! I'll test it out in a bit.

2017-02-27 17:58 UTC, andrewda commented on package.json
>      "mysql": "2.9.0",
Remove unused dependency.

2017-02-27 18:31 UTC, MartijnVegter commented
@andrewda Should be fixed.

2017-02-27 18:33 UTC, andrewda requested changes

2017-02-27 18:33 UTC, andrewda commented on models/Keys.js
> +	premium: String
Make this a boolean

2017-02-27 19:37 UTC, MartijnVegter commented on models/Keys.js
> +	premium: String
Changed it

2017-02-28 10:48 UTC, MartijnVegter commented
This can also fix #13, as it is working as far as I was able to test.

2017-02-28 17:57 UTC, andrewda approved these changes

2017-02-28 17:59 UTC, merged